In [1]:
import numpy
#import kagglehub

In [2]:
#path = kagglehub.dataset_download("hojjatk/mnist-dataset")

In [7]:
import idx2numpy
TEST_IMAGE_FILENAME = r'c:\Users\maxb\OneDrive - Graphcore\Documents\LDL\data\mnist\t10k-images.idx3-ubyte'
TEST_LABEL_FILENAME = r'c:\Users\maxb\OneDrive - Graphcore\Documents\LDL\data\mnist\t10k-labels.idx1-ubyte'
TRAIN_IMAGE_FILENAME = r'c:\Users\maxb\OneDrive - Graphcore\Documents\LDL\data\mnist\train-images.idx3-ubyte'
TRAIN_LABEL_FILENAME = r'c:\Users\maxb\OneDrive - Graphcore\Documents\LDL\data\mnist\train-labels.idx1-ubyte'

# Read files.
train_images = idx2numpy.convert_from_file(
    TRAIN_IMAGE_FILENAME)
train_labels = idx2numpy.convert_from_file(
    TRAIN_LABEL_FILENAME)
test_images = idx2numpy.convert_from_file(TEST_IMAGE_FILENAME)
test_labels = idx2numpy.convert_from_file(TEST_LABEL_FILENAME)

# Print dimensions.
print('dimensions of train_images: ', train_images.shape)
print('dimensions of train_labels: ', train_labels.shape)
print('dimensions of test_images: ', test_images.shape)
print('dimensions of test_labels: ', test_labels.shape)


dimensions of train_images:  (60000, 28, 28)
dimensions of train_labels:  (60000,)
dimensions of test_images:  (10000, 28, 28)
dimensions of test_labels:  (10000,)


In [ ]:
# Print one training example.
print('label for first training example: ', train_labels[0])
print('---beginning of pattern for first training example---')
for line in train_images[420]:
    #print(line)
    for num in line:
        if num > 0:
            print('*', end = ' ')
        else:
            print(' ', end = ' ')
    print('')
print('---end of pattern for first training example---')

label for first training example:  5
---beginning of pattern for first training example---
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                                                        
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                                                        
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                                                        
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                                                        
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                                                        
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
                                                        
[  0   0   0   0   0   0   0   0   0   0   0   0  17  66 138 255 253 253
 253 201 127   0   0   0   0   0   0   0]
                        * * * * * * * * *               
[  0   0   0   0   0   0   0   0   0   0   0  5